services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        # image: ekasatriaap/apc:8.2.19
        container_name: cash-flow-app
        env_file: .env
        ports:
            - "8080:8000"
        volumes:
            - ./:/app
            # - ./docker-compose/apache:/etc/apache2/sites-available
        command: bash -c "php artisan octane:frankenphp"
        networks:
            - cash-flow-network

    mariadb:
        image: mariadb
        container_name: mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: el.psy.congroo
        volumes:
            - mariadb-data:/var/lib/mysql
        networks:
            - cash-flow-network

volumes:
    mariadb-data:

networks:
    cash-flow-network:
