services:
    app:
        build: .
        container_name: cash-flow-app
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        networks:
            - cash-flow-network

    mariadb:
        image: mariadb
        container_name: mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: el.psy.congroo
        volumes:
            - mariadb-data:/var/lib/mysql
        networks:
            - cash-flow-network

volumes:
    mariadb-data:

networks:
    cash-flow-network:
