services:
    app:
        build: .
        container_name: cash-flow-app
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker-compose/apache:/etc/apache2/sites-available/
            - ./docker-compose/php:/usr/local/etc/php/
        networks:
            - cash-flow-network

    mariadb:
        image: mariadb
        container_name: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: el.psy.congroo
        volumes:
            - mariadb-data:/var/lib/mysql
        networks:
            - cash-flow-network

    adminer:
        image: adminer
        container_name: adminer
        ports:
            - 8081:8080
        networks:
            - cash-flow-network

volumes:
    mariadb-data:

networks:
    cash-flow-network:
